FROM debian:trixie-slim

RUN set -x \
    && apt install debian-keyring debian-archive-keyring \
    && apt-get update 

RUN set -x \
    && apt-get install -y openjdk-21-jre-headless 

RUN set -x \
    && apt-get install -y wget inetutils-ping netcat

RUN set -x \
    && apt-get autoremove -y wget \
    && rm -rf /var/lib/apt/lists/*
